apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets: 
        - name: registry.imaginelearning.net
      containers:
        - name: k8s-hands-on
          image: registry.imaginelearning.net/ilprovo/k8s-hands-on:test1
          imagePullPolicy: IfNotPresent
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend-k8s-hands-on
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30036
                                            
